//***************************************************************************************************                                                                                                                                                                                                     
//系统提示文本    0x00010000                                                                                                                                                                                                                                                                              
#define DS_SOFTWARE_VERSION					   		0x00010000      //  MTC(PND) V1.0                                                                                                                                                                                                                     
#define DS_COMPANY_NAME					   			0x00010001      // 深圳市车易通科技有限公司版权所有                                                                                                                                                                                                   
#define DS_COMPANY_WEBSIT				   			0x00010002      // 公司网址：www.v-checker.com                                                                                                                                                                                                        
#define DS_COMPANY_TEL					   			0x00010003      // 服务热线：400-6363-301                                                                                                                                                                                                             
#define DS_FILE_OPEN_ERR				   			0x00010004      // 文件打开失败!                                                                                                                                                                                                                      
#define DS_INIT_APP_SET_ERR				   			0x00010005      // 初始化软件配置文件失败!                                                                                                                                                                                                            
#define DS_INIT_ECU_SET_ERR				   			0x00010006      // 初始化ECU配置文件失败!                                                                                                                                                                                                             
#define DS_CHECK_ECU_MODEL				   			0x00010007      // 检测通讯协议...                                                                                                                                                                                                                    
#define DS_CHECK_ECU_MODEL_ERR			   			0x00010008      // 通讯协议设置失败!                                                                                                                                                                                                                  
#define DS_INIT_B302					   			0x00010009      // 初始化系统参数...                                                                                                                                                                                                                  
#define DS_INIT_B302_ERR				   			0x0001000A      // 初始化系统参数失败!                                                                                                                                                                                                                
#define DS_ENTER_ECU					   			0x0001000B      // 进入电控系统...                                                                                                                                                                                                                    
#define DS_ENTER_ECU_ERR				   			0x0001000C      // 进入电控系统失败!                                                                                                                                                                                                                  
#define DS_INIT_APP_UI					   			0x0001000D      // 初始化软件界面...                                                                                                                                                                                                                  
#define DS_GET_ECU_DATA					   			0x0001000E		// 获取汽车数据...                                                                                                                                                                                                                    
#define DS_GET_ECU_DATA_ERR				   			0x0001000F		// 获取汽车数据失败!                                                                                                                                                                                                                  
#define DS_RE_GET_ECU_DATA				   			0x00010010		// 重新进入电控系统...                                                                                                                                                                                                                
#define DS_SAVE_APP_DATA				   			0x00010011		// 正在保存软件数据...                                                                                                                                                                                                                
#define DS_EXIT_APP						   			0x00010012		// 退出软件...                                                                                                                                                                                                                        
#define DS_ALARM_SHIFT					   			0x00010013		// 请及时换挡                                                                                                                                                                                                                         
#define DS_ALARM_OVERSPEED				   			0x00010014		// 请勿超速驾驶                                                                                                                                                                                                                       
#define DS_ALARM_FUEL_SHORTAGE			   			0x00010015		// 油箱油量不足                                                                                                                                                                                                                       
#define DS_ALARM_WATER_TEMP				   			0x00010016		// 车辆水温过高                                                                                                                                                                                                                       
#define DS_ALARM_FATIGUE_DRIVING		   			0x00010017		// 请勿疲劳驾驶                                                                                                                                                                                                                       
#define DS_ALARM_VOLT_LOW				   			0x00010018		// 电瓶电压过低                                                                                                                                                                                                                       
#define DS_ALARM_VOLT_HIGH				   			0x00010019		// 电瓶电压过高                                                                                                                                                                                                                       
#define DS_GPS_COM_SUCCESS				   			0x0001001A		// 打开GPS数据串口成功                                                                                                                                                                                                                
#define DS_GPS_COM_FAILURE				   			0x0001001B		// 打开GPS数据串口失败   
#define DS_ECU_COM_INIT					   			0x0001001C		// 正在获取汽车数据,请稍后.
#define DS_ECU_COM_FAILURE				   			0x0001001D		// 获取汽车数据失败!                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                          
//功能按钮      0x00012000                 			                                                                                                                                                                                                                                                      
#define DS_BTN_EXIT						   			0x00012000		//退出                                                                                                                                                                                                                                
#define DS_BTN_OK						   			0x00012001		//确定                                                                                                                                                                                                                                
#define DS_BTN_PAGE_UP					   			0x00012002		//上一页                                                                                                                                                                                                                              
#define DS_BTN_PAGE_DOWN				   			0x00012003		//下一页                                                                                                                                                                                                                              
#define DS_BTN_AUTO_SCAN				   			0x00012004		//自动扫描                                                                                                                                                                                                                            
#define DS_BTN_RETURN					   			0x00012005		//返回                                                                                                                                                                                                                                
#define DS_BTN_OPEN						   			0x00012006		//打开                                                                                                                                                                                                                                
#define DS_BTN_CLOSE					   			0x00012007		//关闭                                                                                                                                                                                                                                
#define DS_BTN_MODIFY					   			0x00012008		//修改                                                                                                                                                                                                                                
#define DS_BTN_NEXT						   			0x00012009 		//下一步                                                                                                                                                                                                                              
#define DS_BTN_NORMAL					   			0x0001200A 		//普通                                                                                                                                                                                                                                
#define DS_BTN_HIGH						   			0x0001200B 		//高温                                                                                                                                                                                                                                
#define DS_BTN_UNCLEAR					   			0x0001200C 		//不清楚      
#define DS_BTN_ITEM_UP					   			0x0001200D		//上一条
#define DS_BTN_ITEM_DOWN				   			0x0001200E		//下一条    
#define DS_BTN_CALIBRATE 				   			0x0001200F		//校准   
#define DS_BTN_RETRY					   			0x00012010		//重试  
#define DS_BTN_DAY	 					   			0x00012011		//白天 
#define DS_BTN_NIGHT					   			0x00012012		//晚上

//界面文本     0x00011000                  			                                                                                                                                                                                                                                                      
#define DS_WEEK_SUN						   			0x00011001		//星期日                                                                                                                                                                                                                              
#define DS_WEEK_MON						   			0x00011002		//星期一                                                                                                                                                                                                                              
#define DS_WEEK_TUES					   			0x00011003		//星期二                                                                                                                                                                                                                              
#define DS_WEEK_WED						   			0x00011004		//星期三                                                                                                                                                                                                                              
#define DS_WEEK_THURS					   			0x00011005		//星期四                                                                                                                                                                                                                              
#define DS_WEEK_FRIDAY					   			0x00011006		//星期五                                                                                                                                                                                                                              
#define DS_WEEK_STA						   			0x00011007		//星期六                                                                                                                                                                                                                              
#define DS_MAIN_IDEL					   			0x00011008		//怠速                                                                                                                                                                                                                                
#define DS_MAIN_TOUR					   			0x00011009		//巡航                                                                                                                                                                                                                                
#define DS_MIAN_RACE					   			0x0001100A		//竞技                                                                                                                                                                                                                                
#define DS_MAIN_DETAIL					   			0x0001100B		//明细                                                                                                                                                                                                                                
#define DS_MAIN_CONFIG					   			0x0001100C		//设置                                                                                                                                                                                                                                
#define DS_MAIN_BACK					   			0x0001100D		//后台                                                                                                                                                                                                                                
#define DS_MAIN_EXIT					   			0x0001100E		//退出                                                                                                                                                                                                                                
#define DS_THE_TOTAL_MILEAGE			   			0x0001100F		//本次行车里程(Km)                                                                                                                                                                                                                    
#define DS_THE_AVG_FUEL_CONSUMPTION		   			0x00011010		//本次平均油耗(L/100Km)                                                                                                                                                                                                               
#define DS_THE_FUEL_CONSUMPTION			   			0x00011011		//本次油耗量(升)                                                                                                                                                                                                                      
#define DS_THE_FUEL_COSTS				   			0x00011012		//本次行车油费(元)                                                                                                                                                                                                                    
#define DS_THE_COSTS_FOR_KM				   			0x00011013		//本次每公里花费(元)                                                                                                                                                                                                                  
#define DS_TOTAL_MILEAGE				   			0x00011014		//总里程(Km)                                                                                                                                                                                                                          
#define DS_AVG_FUEL_CONSUMPTION			   			0x00011015		//历史平均油耗(L/100Km)                                                                                                                                                                                                               
#define DS_FUEL_CONSUMPTION				   			0x00011016		//历史油耗量(升)                                                                                                                                                                                                                      
#define DS_FUEL_COSTS					   			0x00011017		//总行车油费(元)                                                                                                                                                                                                                      
#define DS_COSTS_FOR_KM					   			0x00011018		//累计每公里花费(元)                                                                                                                                                                                                                  
#define DS_EUC_MODEL_TITLE				   			0x00011019		//协议设置                                                                                                                                                                                                                            
#define DS_EUC_MODEL_NAME				   			0x00011020		//名称                                                                                                                                                                                                                                
#define DS_EUC_MODEL_VERSION			   			0x00011021		//版本                                                                                                                                                                                                                                
#define DS_EUC_MODEL_SELECT				   			0x00011022		//选择                                                                                                                                                                                                                                
#define DS_CONFIG_DEVICES_TITLE			   			0x00011023      //系统设置                                                                                                                                                                                                                            
#define DS_CONFIG_ALARM_OVERSPEED		   			0x00011024      //超速报警                                                                                                                                                                                                                            
#define DS_CONFIG_ALARM_WATER_TEMP		   			0x00011025      //水温报警                                                                                                                                                                                                                            
#define DS_CONFIG_ALARM_FATIGUE_DRIVING	   			0x00011026      //疲劳驾驶                                                                                                                                                                                                                            
#define DS_CONFIG_ALARM_BATTERY_VOLTAGE		   		0x00011027      //电瓶电压                                                                                                                                                                                                                            
#define DS_CONFIG_ALARM_TROUBLE		   				0x00011028      //故障报警                                                                                                                                                                                                                            
#define DS_CONFIG_START_SET	   						0x00011029      //启动设置                                                                                                                                                                                                                            
#define DS_CONFIG_FUEL_CALIBRATION		   			0x0001102A      //油耗校准                                                                                                                                                                                                                            
#define DS_CONFIG_FUEL_PRICE		   				0x0001102B      //油价调整                                                                                                                                                                                                                            
#define DS_CONFIG_DEVICES_FACTORY_SET				0x0001102C      //出厂设置                                                                                                                                                                                                                            
#define DS_CONFIG_DEVICES_VERSION		   			0x0001102D      //版本信息                                                                                                                                                                                                                            
#define DS_CONFIG_02E   							0x0001102E      //                                                                                                                                                                                                                                    
#define DS_CONFIG_02F   							0x0001102F      //                                                                                                                                                                                                                                    
#define DS_CONFIG_030   							0x00011030      //                                                                                                                                                                                                                                    
#define DS_CONFIG_031   							0x00011031      //                                                                                                                                                                                                                                    
#define DS_CONFIG_032   							0x00011032      //                                                                                                                                                                                                                                    
#define DS_CONFIG_033   							0x00011033      //                                                                                                                                                                                                                                    
#define DS_CONFIG_034   							0x00011034      //                                                                                                                                                                                                                                    
#define DS_CONFIG_035   							0x00011035      //                                                                                                                                                                                                                                    
#define DS_CONFIG_036   							0x00011036      //                                                                                                                                                                                                                                    
#define DS_CONFIG_037   							0x00011037      //                                                                                                                                                                                                                                    
#define DS_CONFIG_038   							0x00011038      //                                                                                                                                                                                                                                    
#define DS_CONFIG_039   							0x00011039      //                                                                                                                                                                                                                                    
#define DS_CONFIG_03A   							0x0001103A      //                                                                                                                                                                                                                                    
#define DS_CONFIG_03B   							0x0001103B      //                                                                                                                                                                                                                                    
#define DS_CONFIG_03C   							0x0001103C      //                                                                                                                                                                                                                                    
#define DS_CONFIG_03D   							0x0001103D      //                                                                                                                                                                                                                                    
#define DS_CONFIG_03E   							0x0001103E      //                                                                                                                                                                                                                                    
#define DS_CONFIG_03F   							0x0001103F      //                                                                                                                                                                                                                                    
#define DS_CONFIG_040   							0x00011040      //                                                                                                                                                                                                                                    
#define DS_CONFIG_041   							0x00011041      //                                                                                                                                                                                                                                    
#define DS_CONFIG_042   							0x00011042      //                                                                                                                                                                                                                                    
#define DS_CONFIG_043   							0x00011043      //                                                                                                                                                                                                                                    
#define DS_CONFIG_044   							0x00011044      //                                                                                                                                                                                                                                    
#define DS_CONFIG_045   							0x00011045      //                                                                                                                                                                                                                                    
#define DS_CONFIG_046   							0x00011046      //                                                                                                                                                                                                                                    
#define DS_CONFIG_047   							0x00011047      //                                                                                                                                                                                                                                    
#define DS_CONFIG_048   							0x00011048      //                                                                                                                                                                                                                                    
#define DS_CONFIG_049   							0x00011049      //                                                                                                                                                                                                                                    
#define DS_CONFIG_04A   							0x0001104A      //                                                                                                                                                                                                                                    
#define DS_CONFIG_04B   							0x0001104B      //                                                                                                                                                                                                                                    
#define DS_CONFIG_04C   							0x0001104C      //                                                                                                                                                                                                                                    
#define DS_CONFIG_04D   							0x0001104D      //                                                                                                                                                                                                                                    
#define DS_CONFIG_04E   							0x0001104E      //                                                                                                                                                                                                                                    
#define DS_CONFIG_STAY_TIME_TITLE		   			0x0001104F		//待机延时                                                                                                                                                                                                                            
#define DS_CONFIG_STAY_TIME_TEXT1		   			0x00011050		//                                                                                                                                                                                                                                    
#define DS_CONFIG_STAY_TIME_TEXT2		   			0x00011051		//待机时间(秒)：                                                                                                                                                                                                                      
#define DS_CONFIG_ERR_LOG_TITLE			   			0x00011052		//错误日志                                                                                                                                                                                                                            
#define DS_CONFIG_ERR_LOG_TEXT1			   			0x00011053		//记录车辆行驶过程中出现的错误信息，建议用户关闭该项功能。                                                                                                                                                                            
#define DS_CONFIG_ERR_LOG_TEXT2			   			0x00011054		//功能状态：                                                                                                                                                                                                                          
#define DS_CONFIG_ALARM_TROUBLE_TITLE	   			0x00011055		//故障报警                                                                                                                                                                                                                            
#define DS_CONFIG_ALARM_TROUBLE_TEXT1	   			0x00011056		//当前车辆出现故障时系统是否自动报警？建议用户打开该项功能。                                                                                                                                                                          
#define DS_CONFIG_ALARM_TROUBLE_TEXT2	   			0x00011057		//功能状态：                                                                                                                                                                                                                          
#define DS_CONFIG_ALARM_WATER_TEMP_TITLE			0x00011058		//水温报警                                                                                                                                                                                                                            
#define DS_CONFIG_ALARM_WATER_TEMP_TEXT1			0x00011059      //                                                                                                                                                                                                                                    
#define DS_CONFIG_ALARM_WATER_TEMP_TEXT2			0x0001105A		//报警值(℃)：                                                                                                                                                                                                                        
#define DS_CONFIG_ALARM_FATIGUE_DRIVING_TITLE		0x0001105B		//疲劳驾驶报警                                                                                                                                                                                                                        
#define DS_CONFIG_ALARM_FATIGUE_DRIVING_TEXT1		0x0001105C		//                                                                                                                                                                                                                                    
#define DS_CONFIG_ALARM_FATIGUE_DRIVING_TEXT2		0x0001105D		//报警值(分钟)：                                                                                                                                                                                                                      
#define DS_CONFIG_ALARM_OVERSPEED_TITLE				0x0001105E		//超速报警                                                                                                                                                                                                                            
#define DS_CONFIG_ALARM_OVERSPEED_TEXT1				0x0001105F      //                                                                                                                                                                                                                                    
#define DS_CONFIG_ALARM_OVERSPEED_TEXT2				0x00011060		//报警值(Km/h)：                                                                                                                                                                                                                      
#define DS_CONFIG_ALARM_SHIFT_REMIND_TITLE			0x00011061		//换挡提醒                                                                                                                                                                                                                            
#define DS_CONFIG_ALARM_SHIFT_REMIND_TEXT1			0x00011062		//换挡转速(Rpm)：                                                                                                                                                                                                                     
#define DS_CONFIG_ALARM_SHIFT_REMIND_TEXT2			0x00011063		//换挡车速(Km/h)：                                                                                                                                                                                                                    
#define DS_CONFIG_ALARM_BATTERY_VOLTAGE_TITLE		0x00011064		//电瓶电压报警                                                                                                                                                                                                                        
#define DS_CONFIG_ALARM_BATTERY_VOLTAGE_TEXT1		0x00011065		//电压下限(V)：                                                                                                                                                                                                                       
#define DS_CONFIG_ALARM_BATTERY_VOLTAGE_TEXT2		0x00011066		//电压上限(V)：                                                                                                                                                                                                                       
#define DS_CONFIG_TEST_TROUBLE_CLEAR_TITLE			0x00011067		//清除故障                                                                                                                                                                                                                            
#define DS_CONFIG_TEST_TROUBLE_CLEAR_TEXT1			0x00011068		//测试条件：关闭发动机，打开点火钥匙                                                                                                                                                                                                  
#define DS_CONFIG_TEST_TROUBLE_CLEAR_TEXT2			0x00011069		//清除故障后所有的故障信息将丢失，继续吗？                                                                                                                                                                                            
#define DS_CONFIG_TEST_SPEED_TITLE					0x0001106A 		//车辆加速测试                                                                                                                                                                                                                        
#define DS_CONFIG_TEST_SPEED_TEXT1					0x0001106B		//起始车速(Km/h)：                                                                                                                                                                                                                    
#define DS_CONFIG_TEST_SPEED_TEXT2					0x0001106C 		//终止车速(Km/h)：                                                                                                                                                                                                                    
#define DS_CONFIG_TEST_SPEED_ING					0x0001106D		//车辆加速测试中...                                                                                                                                                                                                                   
#define DS_CONFIG_TEST_SPEED_END					0x0001106E 		//车辆加速测试完成！                                                                                                                                                                                                                  
#define DS_CONFIG_TEST_DISTANCE_TITLE				0x0001106F 		//车辆距离测试                                                                                                                                                                                                                        
#define DS_CONFIG_TEST_DISTANCE_TEXT1				0x00011070 		//                                                                                                                                                                                                                                    
#define DS_CONFIG_TEST_DISTANCE_TEXT2				0x00011071 		//测试距离(m)：                                                                                                                                                                                                                       
#define DS_CONFIG_TEST_DISTANCE_ING					0x00011072 		//车辆距离测试中...                                                                                                                                                                                                                   
#define DS_CONFIG_TEST_DISTANCE_END					0x00011073 		//车辆距离测试完成！                                                                                                                                                                                                                  
#define DS_CONFIG_FUEL_CALIBRATION_TITLE			0x00011074  	//油耗校准                                                                                                                                                                                                                            
#define DS_CONFIG_FUEL_CALIBRATION_TEXT1			0x00011075  	//即时油耗系数：                                                                                                                                                                                                                      
#define DS_CONFIG_FUEL_CALIBRATION_TEXT2			0x00011076  	//平均油耗系数：                                                                                                                                                                                                                      
#define DS_CONFIG_FUEL_CLEAR_TITLE					0x00011077  	//历史油耗清零                                                                                                                                                                                                                        
#define DS_CONFIG_FUEL_CLEAR_TEXT1					0x00011078      //                                                                                                                                                                                                                                    
#define DS_CONFIG_FUEL_CLEAR_TEXT2					0x00011079  	//历史油耗清零后所有的油耗相关信息丢失，继续吗？                                                                                                                                                                                      
#define DS_CONFIG_FUEL_ENTER_TITLE					0x0001107A  	//手动输入油量                                                                                                                                                                                                                        
#define DS_CONFIG_FUEL_ENTER_TEXT1					0x0001107B  	//当前油量值(升)：                                                                                                                                                                                                                    
#define DS_CONFIG_FUEL_ENTER_TEXT2					0x0001107C  	//油量报警值(升)：                                                                                                                                                                                                                    
#define DS_CONFIG_FUEL_PRICE_TITLE					0x0001107D  	//调整油价                                                                                                                                                                                                                            
#define DS_CONFIG_FUEL_PRICE_TEXT1					0x0001107E   	//                                                                                                                                                                                                                                    
#define DS_CONFIG_FUEL_PRICE_TEXT2					0x0001107F  	//当前油价(元/升)：                                                                                                                                                                                                                   
#define DS_CONFIG_TEST_UNIT_SPEED					0x00011080		//车速(公里/时)                                                                                                                                                                                                                       
#define DS_CONFIG_TEST_UNIT_DISTANCE				0x00011081		//距离(米)                                                                                                                                                                                                                            
#define DS_CONFIG_TEST_UNIT_TIME					0x00011082		//时间(秒)                                                                                                                                                                                                                            
#define DS_CONFIG_FUEL_NOW_TITLE					0x00011083 		// 即时油耗校准                                                                                                                                                                                                                       
#define DS_CONFIG_FUEL_NOW_TIP1						0x00011084 		// 　　为了让智能行车电脑更及时、更准确的显示车辆的即时油耗，可以对系统进行即时油耗系数的调整。                                                                                                                                       
#define DS_CONFIG_FUEL_NOW_TIP2						0x00011085 		// 　　根据车辆硬件配置（如：排量、手动/自动档等），查询该车辆的制造厂家对外发布的等速油耗值（如：奥迪/2012款/2.0T/手自一体，80Km/h等速油耗值8-9升）                                                                                  
#define DS_CONFIG_FUEL_NOW_SETUP_TITLE				0x00011086 		// 等速油耗值                                                                                                                                                                                                                         
#define DS_CONFIG_FUEL_NOW_SETUP_TEXT1				0x00011087  	// 速度(Km/h)：                                                                                                                                                                                                                       
#define DS_CONFIG_FUEL_NOW_SETUP_TEXT2				0x00011088  	// 油耗(L/100Km)：                                                                                                                                                                                                                    
#define DS_CONFIG_FUEL_NOW_TEST_TITLE				0x00011089  	// 车速 & 油耗                                                                                                                                                                                                                        
#define DS_CONFIG_FUEL_NOW_TEST_TEXT1				0x0001108A  	// 当前车速：                                                                                                                                                                                                                         
#define DS_CONFIG_FUEL_NOW_TEST_TEXT2				0x0001108B      // 系统油耗：                                                                                                                                                                                                                         
#define DS_CONFIG_FUEL_NOW_TIP_KEEP_RUN				0x0001108C  	// 请在水平路况上\r\n按厂商公布车速匀速行驶                                                                                                                                                                                           
#define DS_CONFIG_FUEL_NOW_TIP_KEPP_TIME			0x0001108D 		// 请保持该车速8秒                                                                                                                                                                                                                    
#define DS_CONFIG_FUEL_AVG_TITLE					0x0001108E  	// 平均油耗校准                                                                                                                                                                                                                       
#define DS_CONFIG_FUEL_AVG_TIP1						0x0001108F  	// 　　如果系统显示的平均油耗不准确，请严格的按照如下步骤进行设置：\r\n　　步骤一：调整即时油耗系数，保证系统的即时油耗显示准确。\r\n　　步骤二：在设置新的即时油耗系数情况下，为了获取准确的平均油耗值，车辆必须行驶超过400公里以上。
#define DS_CONFIG_FUEL_AVG_TIP2						0x00011090  	// 　　根据车辆硬件配置（如：排量、手动/自动档等），查询该车辆的制造厂家对外发布或者用户自己测算的综合工况平均油耗值（如：奥迪/2012款/2.0T/手自一体，综合工况平均油耗7.6L/100Km）                                                     
#define DS_CONFIG_FUEL_AVG_SETUP_TITLE				0x00011091   	// 综合工况平均油耗                                                                                                                                                                                                                   
#define DS_CONFIG_FUEL_AVG_SETUP_TEXT1				0x00011092                                                                                                                                                                                                                                            
#define DS_CONFIG_FUEL_AVG_SETUP_TEXT2				0x00011093 		// 综合工况平均油耗：                                                                                                                                                                                                                 
#define DS_CONFIG_FUEL_AVG_TEST_TITLE				0x00011094 		// 平均油耗校准                                                                                                                                                                                                                       
#define DS_CONFIG_FUEL_AVG_TEST_TEXT1				0x00011095 		// 正确的综合平均油耗：                                                                                                                                                                                                               
#define DS_CONFIG_FUEL_AVG_TEST_TEXT2				0x00011096 		// 系统显示的平均油耗：                                                                                                                                                                                                               
#define DS_CONFIG_FUEL_AVG_TIP_UPDATE				0x00011097 		// 是否重新计算平均油耗系数？                                                                                                                                                                                                         
#define DS_CONFIG_FUEL_CALIBARATION_OK				0x00011098  	// 设置完成                                                                                                                                                                                                                           
#define DS_CONFIG_SHOW_DATA_TITLE					0x00011099  	// 配置显示数据                                                                                                                                                                                                                       
#define DS_CONFIG_SHOW_DATA_NAME					0x0001109A  	// 配置文本                                                                                                                                                                                                                           
#define DS_CONFIG_SHOW_DATA_ID						0x0001109B  	// 编码                                                                                                                                                                                                                               
#define DS_CONFIG_SHOW_DATA_UNIT					0x0001109C  	// 单位                                                                                                                                                                                                                               
#define DS_CONFIG_SHOW_DATA_SEL						0x0001109D  	// 选择           
#define DS_SETUP_GUIDE_TITLE						0x0001109E		// 设置向导
#define DS_SETUP_GUIDE_TIP_INIT						0x0001109F		// 第一次使用仪器,必须对仪器进行初始化设置。
#define DS_SETUP_GUIDE_TIP_START_CAR				0x00011100		// 请发动汽车,按"下一步"系统将自动检测车辆通讯协议。
#define DS_SETUP_GUIDE_TIP_SET_FUEL_PRICE			0x00011101		// 由于国际油价经常波动，导致不同时期的油价差别很大，为了能够准确的计算行驶的燃油花费，需要正确的输入油价值。
#define DS_SETUP_GUIDE_TIP_SET_ENGINE				0x00011102		// 车辆型号不同其对应的发动机是不一样的，将导致车辆在运行过程中发动机的水温差别很大，需要根据发动机的情况设置对应的水温报警值。
#define DS_SETUP_GUIDE_ENGINE_TEXT1					0x00011103		// ● 普通发动机(100℃)
#define DS_SETUP_GUIDE_ENGINE_TEXT2					0x00011104		// ● 高温发动机(110℃)
#define DS_SETUP_GUIDE_TIP_FULE_COEFFICIENT			0x00011105		// 不同排量的车型其对应的油耗是不同的，需要设置对应的油耗系数。该系数仅为理论值，如果在使用过程中发现不精准，可以自行标定。请选择排量：
#define DS_SETUP_GUIDE_FULE_COEFFICIENT_TEXT1		0x00011106		// 1.00以下
#define DS_SETUP_GUIDE_FULE_COEFFICIENT_TEXT2		0x00011107		// 1.01-1.29
#define DS_SETUP_GUIDE_FULE_COEFFICIENT_TEXT3		0x00011108		// 1.30-1.59
#define DS_SETUP_GUIDE_FULE_COEFFICIENT_TEXT4		0x00011109		// 1.60-1.79
#define DS_SETUP_GUIDE_FULE_COEFFICIENT_TEXT5		0x0001110A		// 1.80-2.00
#define DS_SETUP_GUIDE_FULE_COEFFICIENT_TEXT6		0x0001110B		// 2.01-2.39
#define DS_SETUP_GUIDE_FULE_COEFFICIENT_TEXT7		0x0001110C		// 2.40-2.69
#define DS_SETUP_GUIDE_FULE_COEFFICIENT_TEXT8		0x0001110D		// 2.70-2.99
#define DS_SETUP_GUIDE_FULE_COEFFICIENT_TEXT9		0x0001110E		// 3.00以上
#define DS_SETUP_GUIDE_DSA_TITLE					0x0001110F		// 雷达安全预警
#define DS_SETUP_GUIDE_GPS_TITLE					0x00011110		// GPS导航
#define DS_SETUP_GUIDE_DSA_NAME						0x00011111		// 软件名称
#define DS_SETUP_GUIDE_DSA_PATH						0x00011112		// 软件路径
#define DS_SETUP_GUIDE_DSA_SEL						0x00011113		// 选择
#define DS_SETUP_GUIDE_OK							0x00011114		// 设置完成，点击“确定”启动系统。
#define DS_SETUP_LAN_TITLE							0x00011115		// 语言设置
#define DS_SETUP_LAN_ID								0x00011116		// 简称
#define DS_SETUP_LAN_NAME							0x00011117		// 语言
#define DS_SETUP_LAN_SEL							0x00011118		// 选择
#define DS_SETUP_FACTORY_SET_TITLE					0x00011119		// 出厂设置
#define DS_SETUP_FACTORY_SET_TEXT					0x0001111A		// 恢复出厂设置后将清除所有配置信息，继续吗？
#define DS_SETUP_AUTO_START_TITLE					0x0001111B		//自动启动
#define DS_SETUP_AUTO_START_NAME					0x0001111C		//软件名称
#define DS_SETUP_AUTO_START_PATH					0x0001111D		//软件路径
#define DS_SETUP_AUTO_START_SEL						0x0001111E		//自动启动
#define DS_SETUP_DEVICES_TIP						0x0001111F		//请参考以上的安装示意图，正确的连接仪器！
#define DS_DTC_INFO_TITLE							0x00011120		//故障信息
#define DS_DTC_INFO_TEXT1							0x00011121		//故障代码：
#define DS_DTC_INFO_TEXT2							0x00011122		//故障信息：
#define DS_SETUP_BACKLIGHT_TITLE					0x00011123		//背光设置